### ISSUE TITLE
letter 'q' has the tail on the opposite side

### ISSUE THREAD

**Issue by HangrySensei** [jamespgilbert/comment-labels#3]
right now, the letter 'q' becomes
//===================
//                   
//   #####         
//  ##   ##        
//  ##   ##        
//   #####         
//  ##             
//                   
//===================

i think it should be the following??
//===================
//                   
//   #####         
//  ##   ##        
//  ##   ##        
//   #####         
//........... ##             
//                   
//===================

**Comment by HangrySensei** [comment]
added the ....... above b/c github deleted all the space

i think you get the idea though, 'Q' should have he tail on the right side, not left side

**Comment by jamespgilbert** [comment]
Great point. I'm surprised no one has noticed that until now.

I will update this after I'm back from traveling.

Thank you for your feedback,
James

**Comment by jamespgilbert** [comment]
All set with the latest commit. Thank you for your feedback.
